# Site settings
title: cieara meador | cmkm.io
email: cieara@cmkm.io
description: > # this means to ignore newlines until "baseurl:"
    personal & portfolio site for cieara meador
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cmkm.io" # the base hostname & protocol for your site
twitter_username: cmkmeador 
github_username: cmkm 

# Build settings
markdown: kramdown
